### ISSUE TITLE
Автопрефиксер 

### ISSUE THREAD

**Issue by Vitalb25** [FARCER/gulp4-for-frontend#4]
Без этого параметра не добавляет префиксы даже для прода. То либо я туплю, либо только с ним и работает
![image](https://user-images.githubusercontent.com/37478975/78507593-a32bc100-7789-11ea-8136-c4e98dfb8c51.png)

**Comment by FARCER** [comment]
Исправил

**Comment by Vitalb25** [comment]
ну не знаю. префиксы у меня так и не появились, на продакшене тоже

**Comment by FARCER** [comment]
хм. действительно криво отрабатывал. Обновил сейчас условия на ваше из скрина. Теперь должно быть все хорошо
