### ISSUE TITLE
JS-модули

### ISSUE THREAD

**Issue by Vitalb25** [FARCER/gulp4-for-frontend#5]
Предлагаю добавить в данную сборку вебпак для сборки js-модулей

**Comment by FARCER** [comment]
Пока что не планирую добавление вебпака. Сборка именно для верстки. Возможно сделаю отдельную сборку именно на вебпаке

**Comment by Vitalb25** [comment]
Я имел ввиду не вебпак сборку как отдельную, а в эту галп сборку запихнуть вебпак что бы он конкретно отвечал за работу модульного js в верстке. webpack-stream - плагин для галпа
