### ISSUE TITLE
Создание папок через терминал

### ISSUE THREAD

**Issue by Dan-Crane** [FARCER/gulp4-for-frontend#6]
Есть мысль одна(сам реализовать не смог)
Подрубить https://www.npmjs.com/package/mkdirp
и написать таску, которая будет создавать нужные папки в стилях и в паге с нужными файлами

**Comment by Dan-Crane** [comment]
Вот, нашел что-то 
https://github.com/nicothin/NTH-start-project/blob/master/createBlock.js

**Comment by vitalbielik** [comment]
а зачем?) как по мне лишнее усложнение. такое делают только для Pug блоков (компонентов)
и используется для больших проектов

**Comment by FARCER** [comment]
Согласен, на мой взгляд в сборку это добавлять не надо
